window.dashboardData = {
  "sp500": "7,022.95",
  "sp500_chg": "+0.80% vs prev close",
  "vix": "18.17",
  "vix_chg": "-1.03% vs prev close",
  "gold": "4,822.80",
  "gold_chg": "-0.05% vs prev close",
  "oil": "90.94",
  "oil_chg": "-0.37% vs prev close",
  "btc": "75,119.16",
  "btc_chg": "+1.26% vs prev close",
  "usdkrw": "1,475.01",
  "usdkrw_chg": "-0.12% vs prev close",
  "yield_spread": "-",
  "yield_spread_chg": "-",
  "fear_greed": "56",
  "fear_greed_label": "greed",
  "options_expiry": "2026-04-17",
  "options_note": "월간 만기",
  "cpi_yoy": "-",
  "cpi_date": "-",
  "nfp_mom": "-",
  "nfp_date": "-",
  "next_cpi": "-",
  "next_nfp": "-",
  "nextrade_basis": "2026-04-16\n07:53\n기준 정보\nNXT 정규시장 체결기준",
  "nextrade_session": "08:00~08:50",
  "nextrade_change": "0.00%",
  "nextrade_issues": "0",
  "nextrade_volume": "0",
  "nextrade_value": "0",
  "nextrade_note": "* 등락률은 기준시점 대비 시가총액의 증감률임",
  "fedwatch_hold": "동결 -",
  "fedwatch_hike": "변경 -",
  "fedwatch_date": "클릭 시 CME FedWatch 열기",
  "doughcon_level": "DOUGHCON 4",
  "doughcon_location": "ROUND HOUSE",
  "doughcon_status": "ELEVATED WATCH",
  "doughcon_note": "클릭 시 PizzINT 열기",
  "earnings": [
    {
      "date": "2026-04-16",
      "symbol": "NFLX",
      "company": "Netflix, Inc.",
      "eps_estimate": "1.34",
      "time": "AMC"
    },
    {
      "date": "2026-04-16",
      "symbol": "TSM",
      "company": "Taiwan Semiconductor Manufactur",
      "eps_estimate": "3.36",
      "time": "BMO"
    },
    {
      "date": "2026-04-21",
      "symbol": "UNH",
      "company": "UnitedHealth Group Incorporated",
      "eps_estimate": "6.68",
      "time": "BMO"
    },
    {
      "date": "2026-04-22",
      "symbol": "TSLA",
      "company": "Tesla, Inc.",
      "eps_estimate": "0.36",
      "time": "AMC"
    },
    {
      "date": "2026-04-23",
      "symbol": "INTC",
      "company": "Intel Corporation",
      "eps_estimate": "0.01",
      "time": "AMC"
    }
  ],
  "fnguide_reports": [],
  "fnguide_url": "https://comp.fnguide.com/SVO2/ASP/SVD_Report_Summary.asp?pGB=1&gicode=A005930&cID=&MenuYn=Y&ReportGB=&NewMenuID=901&stkGb=701",
  "updated_at": "2026-04-16 07:54:41"
};
