window.dashboardData = {
  "sp500": "7,137.90",
  "sp500_chg": "+1.05% vs prev close",
  "vix": "18.92",
  "vix_chg": "-2.97% vs prev close",
  "gold": "4,748.20",
  "gold_chg": "+1.06% vs prev close",
  "oil": "92.43",
  "oil_chg": "+0.33% vs prev close",
  "btc": "78,599.11",
  "btc_chg": "+2.94% vs prev close",
  "usdkrw": "1,485.80",
  "usdkrw_chg": "+1.13% vs prev close",
  "yield_spread": "-",
  "yield_spread_chg": "-",
  "fear_greed": "68",
  "fear_greed_label": "greed",
  "options_expiry": "2026-04-24",
  "options_note": "주간 만기",
  "cpi_yoy": "-",
  "cpi_date": "-",
  "nfp_mom": "-",
  "nfp_date": "-",
  "next_cpi": "-",
  "next_nfp": "-",
  "nextrade_basis": "2026-04-23\n08:02\n기준 정보\nNXT 정규시장 체결기준",
  "nextrade_session": "08:00~08:50",
  "nextrade_change": "+0.61%",
  "nextrade_issues": "533",
  "nextrade_volume": "9,592,780",
  "nextrade_value": "759,517,172,560",
  "nextrade_note": "* 등락률은 기준시점 대비 시가총액의 증감률임",
  "fedwatch_hold": "동결 -",
  "fedwatch_hike": "변경 -",
  "fedwatch_date": "클릭 시 CME FedWatch 열기",
  "doughcon_level": "DOUGHCON 4",
  "doughcon_location": "ROUND HOUSE",
  "doughcon_status": "ELEVATED WATCH",
  "doughcon_note": "클릭 시 PizzINT 열기",
  "earnings": [
    {
      "date": "2026-04-23",
      "symbol": "INTC",
      "company": "Intel Corporation",
      "eps_estimate": "0.01",
      "time": "AMC"
    },
    {
      "date": "2026-04-29",
      "symbol": "AMZN",
      "company": "Amazon.com, Inc.",
      "eps_estimate": "1.65",
      "time": "AMC"
    },
    {
      "date": "2026-04-29",
      "symbol": "GOOGL",
      "company": "Alphabet Inc.",
      "eps_estimate": "2.62",
      "time": "AMC"
    },
    {
      "date": "2026-04-29",
      "symbol": "META",
      "company": "Meta Platforms, Inc.",
      "eps_estimate": "6.64",
      "time": "AMC"
    },
    {
      "date": "2026-04-29",
      "symbol": "MSFT",
      "company": "Microsoft Corporation",
      "eps_estimate": "4.07",
      "time": "AMC"
    },
    {
      "date": "2026-04-29",
      "symbol": "QCOM",
      "company": "QUALCOMM Incorporated",
      "eps_estimate": "2.56",
      "time": "AMC"
    },
    {
      "date": "2026-04-30",
      "symbol": "AAPL",
      "company": "Apple Inc.",
      "eps_estimate": "1.94",
      "time": "AMC"
    }
  ],
  "fnguide_reports": [],
  "ystreet_title": "YStreet ETF Tracker",
  "ystreet_url": "https://d1rjfvjf23ngm5.cloudfront.net/#dashboard",
  "ystreet_note": "ActiveETF Tracker 대시보드 직접 경로를 사용합니다.",
  "ystreet_market_buy": "-",
  "ystreet_market_sell": "-",
  "ystreet_market_buy_label": "매수 우위",
  "ystreet_market_sell_label": "매도 우위",
  "ystreet_activity": "-",
  "ystreet_activity_label": "활동성 비율",
  "ystreet_activity_note": "※ 전체 ETF 중 종목이 변동된 ETF 비율",
  "ystreet_top_returns": [],
  "ystreet_buy_top10": [],
  "ystreet_sell_top10": [],
  "fnguide_url": "https://comp.fnguide.com/SVO2/ASP/SVD_Report_Summary.asp?pGB=1&gicode=A005930&cID=&MenuYn=Y&ReportGB=&NewMenuID=901&stkGb=701",
  "updated_at": "2026-04-23 08:03:31"
};
